### PR TITLE
add todo mascot in svg and png variants

### PR DESCRIPTION
**Pull request by anajsana**
Signed-off-by: Ana Jimenez Santamaria <ana@todogroup.org>

### CODE REVIEW

**Comment by geekygirldawn** [comment]
I think this is adorable! 

I suspect that this needs to be approved by the LF branding folks to make sure it's consistent with how they want to manage the TODO Group brand.

**Comment by anajsana** [comment]
> I think this is adorable!
> 
> I suspect that this needs to be approved by the LF branding folks to make sure it's consistent with how they want to manage the TODO Group brand.

Thank you! 🙂  yes, I've pinged @caniszczyk for advice on that.

**Comment by caniszczyk** [comment]
LGTM love it and approved! Let's make sure we name them

**Comment by anajsana** [comment]
> LGTM love it and approved! Let's make sure we name them

Ok! I'll go ahead and merge 👍

**Pull request merged**
